[package]
name = "hew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fimg = { version = "0.4.22", features = ["save"], default-features = false }
